name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Lint with pylint
        run: |
          pip install pylint
          pylint main.py || true
          
      - name: Check for common issues
        run: |
          echo "Checking for import issues..."
          python3 -m py_compile main.py

